# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Fashion Design', url: 'fashion-design'}
- {name: 'Natural Dyes',   url: 'natural-dyes'}
- {name: 'Graphic Design', url: 'graphic-design'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/alexandria_meredith'}
- {icon: 'envelope', link:   'mailto:alexandria.meredith@yahoo.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
